title: ... ruben
author: Rubén Romgar
email: ruromgar@gmail.com
url: https://ruromgar.github.io
baseurl: "/"
description: >
  <br> idk <br> 

permalink: /:slug.html

# favicon: "favicon.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
